# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sirius/types/mount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sirius/types/mount.proto',
  package='sirius.types',
  syntax='proto3',
  serialized_options=_b('Z\031go.athera.io/sirius/types'),
  serialized_pb=_b('\n\x18sirius/types/mount.proto\x12\x0csirius.types\"K\n\x05Mount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0emount_location\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x04 \x01(\tB\x1bZ\x19go.athera.io/sirius/typesb\x06proto3')
)




_MOUNT = _descriptor.Descriptor(
  name='Mount',
  full_name='sirius.types.Mount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sirius.types.Mount.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sirius.types.Mount.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mount_location', full_name='sirius.types.Mount.mount_location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='sirius.types.Mount.group_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Mount'] = _MOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mount = _reflection.GeneratedProtocolMessageType('Mount', (_message.Message,), dict(
  DESCRIPTOR = _MOUNT,
  __module__ = 'sirius.types.mount_pb2'
  # @@protoc_insertion_point(class_scope:sirius.types.Mount)
  ))
_sym_db.RegisterMessage(Mount)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
