# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sirius/services/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from athera.sync.sirius.types import file_pb2 as sirius_dot_types_dot_file__pb2
from athera.sync.sirius.types import mount_pb2 as sirius_dot_types_dot_mount__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sirius/services/service.proto',
  package='sirius.services',
  syntax='proto3',
  serialized_options=_b('Z\034go.athera.io/sirius/services'),
  serialized_pb=_b('\n\x1dsirius/services/service.proto\x12\x0fsirius.services\x1a\x17sirius/types/file.proto\x1a\x18sirius/types/mount.proto\"2\n\x10\x46ilesListRequest\x12\x10\n\x08mount_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"U\n\x11\x46ilesListResponse\x12\x10\n\x08mount_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12 \n\x04\x66ile\x18\x03 \x01(\x0b\x32\x12.sirius.types.File\">\n\x19\x46ilesListRepeatedResponse\x12!\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x12.sirius.types.File\"I\n\x13\x46ileContentsRequest\x12\x10\n\x08mount_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x12\n\nchunk_size\x18\x03 \x01(\x03\"<\n\x12\x46ileContentsResult\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\x17\n\x0f\x62ytes_remaining\x18\x02 \x01(\x03\"\x0f\n\rMountsRequest\"3\n\x0cMountsResult\x12#\n\x06mounts\x18\x01 \x03(\x0b\x32\x13.sirius.types.Mount\"6\n\x11\x46ileUploadRequest\x12\x12\n\nchunk_size\x18\x03 \x01(\x03\x12\r\n\x05\x62ytes\x18\x04 \x01(\x0c\"\x14\n\x12\x46ileUploadResponse2\xe5\x02\n\x06Sirius\x12I\n\x06Mounts\x12\x1e.sirius.services.MountsRequest\x1a\x1d.sirius.services.MountsResult\"\x00\x12V\n\tFilesList\x12!.sirius.services.FilesListRequest\x1a\".sirius.services.FilesListResponse\"\x00\x30\x01\x12]\n\x0c\x46ileContents\x12$.sirius.services.FileContentsRequest\x1a#.sirius.services.FileContentsResult\"\x00\x30\x01\x12Y\n\nFileUpload\x12\".sirius.services.FileUploadRequest\x1a#.sirius.services.FileUploadResponse\"\x00(\x01\x42\x1eZ\x1cgo.athera.io/sirius/servicesb\x06proto3')
  ,
  dependencies=[sirius_dot_types_dot_file__pb2.DESCRIPTOR,sirius_dot_types_dot_mount__pb2.DESCRIPTOR,])




_FILESLISTREQUEST = _descriptor.Descriptor(
  name='FilesListRequest',
  full_name='sirius.services.FilesListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mount_id', full_name='sirius.services.FilesListRequest.mount_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='sirius.services.FilesListRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=151,
)


_FILESLISTRESPONSE = _descriptor.Descriptor(
  name='FilesListResponse',
  full_name='sirius.services.FilesListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mount_id', full_name='sirius.services.FilesListResponse.mount_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='sirius.services.FilesListResponse.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='sirius.services.FilesListResponse.file', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=238,
)


_FILESLISTREPEATEDRESPONSE = _descriptor.Descriptor(
  name='FilesListRepeatedResponse',
  full_name='sirius.services.FilesListRepeatedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='sirius.services.FilesListRepeatedResponse.files', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=302,
)


_FILECONTENTSREQUEST = _descriptor.Descriptor(
  name='FileContentsRequest',
  full_name='sirius.services.FileContentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mount_id', full_name='sirius.services.FileContentsRequest.mount_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='sirius.services.FileContentsRequest.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='sirius.services.FileContentsRequest.chunk_size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=377,
)


_FILECONTENTSRESULT = _descriptor.Descriptor(
  name='FileContentsResult',
  full_name='sirius.services.FileContentsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bytes', full_name='sirius.services.FileContentsResult.bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_remaining', full_name='sirius.services.FileContentsResult.bytes_remaining', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=439,
)


_MOUNTSREQUEST = _descriptor.Descriptor(
  name='MountsRequest',
  full_name='sirius.services.MountsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=456,
)


_MOUNTSRESULT = _descriptor.Descriptor(
  name='MountsResult',
  full_name='sirius.services.MountsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mounts', full_name='sirius.services.MountsResult.mounts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=509,
)


_FILEUPLOADREQUEST = _descriptor.Descriptor(
  name='FileUploadRequest',
  full_name='sirius.services.FileUploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='sirius.services.FileUploadRequest.chunk_size', index=0,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='sirius.services.FileUploadRequest.bytes', index=1,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=565,
)


_FILEUPLOADRESPONSE = _descriptor.Descriptor(
  name='FileUploadResponse',
  full_name='sirius.services.FileUploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=587,
)

_FILESLISTRESPONSE.fields_by_name['file'].message_type = sirius_dot_types_dot_file__pb2._FILE
_FILESLISTREPEATEDRESPONSE.fields_by_name['files'].message_type = sirius_dot_types_dot_file__pb2._FILE
_MOUNTSRESULT.fields_by_name['mounts'].message_type = sirius_dot_types_dot_mount__pb2._MOUNT
DESCRIPTOR.message_types_by_name['FilesListRequest'] = _FILESLISTREQUEST
DESCRIPTOR.message_types_by_name['FilesListResponse'] = _FILESLISTRESPONSE
DESCRIPTOR.message_types_by_name['FilesListRepeatedResponse'] = _FILESLISTREPEATEDRESPONSE
DESCRIPTOR.message_types_by_name['FileContentsRequest'] = _FILECONTENTSREQUEST
DESCRIPTOR.message_types_by_name['FileContentsResult'] = _FILECONTENTSRESULT
DESCRIPTOR.message_types_by_name['MountsRequest'] = _MOUNTSREQUEST
DESCRIPTOR.message_types_by_name['MountsResult'] = _MOUNTSRESULT
DESCRIPTOR.message_types_by_name['FileUploadRequest'] = _FILEUPLOADREQUEST
DESCRIPTOR.message_types_by_name['FileUploadResponse'] = _FILEUPLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilesListRequest = _reflection.GeneratedProtocolMessageType('FilesListRequest', (_message.Message,), dict(
  DESCRIPTOR = _FILESLISTREQUEST,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FilesListRequest)
  ))
_sym_db.RegisterMessage(FilesListRequest)

FilesListResponse = _reflection.GeneratedProtocolMessageType('FilesListResponse', (_message.Message,), dict(
  DESCRIPTOR = _FILESLISTRESPONSE,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FilesListResponse)
  ))
_sym_db.RegisterMessage(FilesListResponse)

FilesListRepeatedResponse = _reflection.GeneratedProtocolMessageType('FilesListRepeatedResponse', (_message.Message,), dict(
  DESCRIPTOR = _FILESLISTREPEATEDRESPONSE,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FilesListRepeatedResponse)
  ))
_sym_db.RegisterMessage(FilesListRepeatedResponse)

FileContentsRequest = _reflection.GeneratedProtocolMessageType('FileContentsRequest', (_message.Message,), dict(
  DESCRIPTOR = _FILECONTENTSREQUEST,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FileContentsRequest)
  ))
_sym_db.RegisterMessage(FileContentsRequest)

FileContentsResult = _reflection.GeneratedProtocolMessageType('FileContentsResult', (_message.Message,), dict(
  DESCRIPTOR = _FILECONTENTSRESULT,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FileContentsResult)
  ))
_sym_db.RegisterMessage(FileContentsResult)

MountsRequest = _reflection.GeneratedProtocolMessageType('MountsRequest', (_message.Message,), dict(
  DESCRIPTOR = _MOUNTSREQUEST,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.MountsRequest)
  ))
_sym_db.RegisterMessage(MountsRequest)

MountsResult = _reflection.GeneratedProtocolMessageType('MountsResult', (_message.Message,), dict(
  DESCRIPTOR = _MOUNTSRESULT,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.MountsResult)
  ))
_sym_db.RegisterMessage(MountsResult)

FileUploadRequest = _reflection.GeneratedProtocolMessageType('FileUploadRequest', (_message.Message,), dict(
  DESCRIPTOR = _FILEUPLOADREQUEST,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FileUploadRequest)
  ))
_sym_db.RegisterMessage(FileUploadRequest)

FileUploadResponse = _reflection.GeneratedProtocolMessageType('FileUploadResponse', (_message.Message,), dict(
  DESCRIPTOR = _FILEUPLOADRESPONSE,
  __module__ = 'sirius.services.service_pb2'
  # @@protoc_insertion_point(class_scope:sirius.services.FileUploadResponse)
  ))
_sym_db.RegisterMessage(FileUploadResponse)


DESCRIPTOR._options = None

_SIRIUS = _descriptor.ServiceDescriptor(
  name='Sirius',
  full_name='sirius.services.Sirius',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=590,
  serialized_end=947,
  methods=[
  _descriptor.MethodDescriptor(
    name='Mounts',
    full_name='sirius.services.Sirius.Mounts',
    index=0,
    containing_service=None,
    input_type=_MOUNTSREQUEST,
    output_type=_MOUNTSRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FilesList',
    full_name='sirius.services.Sirius.FilesList',
    index=1,
    containing_service=None,
    input_type=_FILESLISTREQUEST,
    output_type=_FILESLISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FileContents',
    full_name='sirius.services.Sirius.FileContents',
    index=2,
    containing_service=None,
    input_type=_FILECONTENTSREQUEST,
    output_type=_FILECONTENTSRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FileUpload',
    full_name='sirius.services.Sirius.FileUpload',
    index=3,
    containing_service=None,
    input_type=_FILEUPLOADREQUEST,
    output_type=_FILEUPLOADRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIRIUS)

DESCRIPTOR.services_by_name['Sirius'] = _SIRIUS

# @@protoc_insertion_point(module_scope)
